-- Dummy data for Change Order Tracker
-- Run AFTER schema.sql in the Supabase SQL Editor.
-- Safe to re-run: uses ON CONFLICT to upsert.

-- ─── PROJECTS ───────────────────────────────────────────────────
insert into public.projects (id, prefix, name, original_contract, current_contract, sort_order) values
  ('tpsj', 'TPSJ', 'TownePlace Suites — Jackson',       6800000, 6800000, 1),
  ('sybj', 'SYBJ', 'Staybridge Suites — Jackson',       7200000, 7200000, 2),
  ('cwsj', 'CWSJ', 'Candlewood Suites — Jackson',       5400000, 5400000, 3),
  ('his',  'HIS',  'Holiday Inn Express — Stephenville', 4900000, 4900000, 4),
  ('hibr', 'HIBR', 'Hampton Inn — Baton Rouge',          6100000, 6100000, 5),
  ('hwg',  'HWG',  'Homewood Suites — Gonzales',         7800000, 7800000, 6)
on conflict (id) do update set
  prefix = excluded.prefix,
  name   = excluded.name,
  original_contract = excluded.original_contract,
  current_contract  = excluded.current_contract,
  sort_order        = excluded.sort_order;

-- ─── CHANGE ORDERS ──────────────────────────────────────────────
-- 18 dummy COs spread across the 6 hotels, mixing status / type / trade / priority.

insert into public.change_orders (
  id, num, title, type, category, priority, project, status,
  submitted_by, reviewed_by, submitted_date, reviewed_date, executed_date, due_date,
  requested_amt, approved_amt, schedule_impact,
  description, justification,
  linked_rfi, linked_spec, linked_drawing,
  assignees, photos, attachments, comments, line_items,
  owner_markup, gc_markup, is_sub_co, sub_cos
) values
-- ── TPSJ ──
('co_tpsj_001', 'TPSJ-CO-001', 'Unforeseen rock at north foundation',
 'unforeseen', 'sitework', 'high', 'tpsj', 'executed',
 'pm', 'owner', '2026-02-10', '2026-02-18', '2026-02-20', '2026-02-18',
 42500, 42500, 3,
 'Encountered granite bedrock at -6ft during excavation. Blasting required.',
 'Unforeseen subsurface conditions. No rock indicated in original geotech report.',
 'RFI-004', '', 'C-101',
 '["pm","sub2"]'::jsonb, '[]'::jsonb,
 '["Geotech_Addendum.pdf","RFQ_Blasting.pdf"]'::jsonb,
 '[{"author":"owner","text":"Confirmed. Supporting documentation received. Approved.","time":"2 months ago"}]'::jsonb,
 '[{"desc":"Rock blasting — 3 days","qty":3,"unit":"Day","rate":8500,"total":25500},{"desc":"Rock spoil removal — 420 CY","qty":420,"unit":"CY","rate":40,"total":16800},{"desc":"Haul & disposal","qty":1,"unit":"LS","rate":200,"total":200}]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

('co_tpsj_002', 'TPSJ-CO-002', 'Lobby finishes upgrade — premium marble',
 'owner_directed', 'finishes', 'medium', 'tpsj', 'approved',
 'pm', 'owner', '2026-03-01', '2026-03-15', null, '2026-03-10',
 128000, 115000, 0,
 'Owner requests upgrade of Level 1 lobby finishes from allowance spec to premium imported marble, custom millwork, and designer lighting fixtures.',
 'Owner-directed change per meeting notes 2/28/2026.',
 '', 'Spec 09 30 00', 'A-101 Rev C',
 '["pm","owner","arch","sub4"]'::jsonb, '[]'::jsonb,
 '["OwnerApproval_Lobby.pdf","LobbyDesign_RevC.pdf"]'::jsonb,
 '[{"author":"arch","text":"Drawings revised per Addendum 3.","time":"1 month ago"},{"author":"owner","text":"Approved at $115K.","time":"1 month ago"}]'::jsonb,
 '[{"desc":"Premium marble — 1,200 SF","qty":1200,"unit":"SF","rate":48,"total":57600},{"desc":"Custom millwork — reception desk","qty":1,"unit":"LS","rate":32000,"total":32000}]'::jsonb,
 0, 0.08, false, '[]'::jsonb),

('co_tpsj_003', 'TPSJ-CO-003', 'MEP redesign — relocated sprinkler main Level 3',
 'design_change', 'mep', 'high', 'tpsj', 'under_review',
 'sub3', 'arch', '2026-04-01', null, null, '2026-04-14',
 18750, 0, 5,
 'Sprinkler main relocated 8ft east on Level 3 to clear structural beam.',
 'Structural beam added per CO-007 conflicts with original sprinkler main routing.',
 'RFI-018', 'Spec 21 13 00', 'FP-301',
 '["pm","sub3","arch"]'::jsonb, '[]'::jsonb,
 '["SK-14_Reroute.pdf","MEP_Coord_Sketch.pdf"]'::jsonb,
 '[{"author":"sub3","text":"Submitted with full backup.","time":"2 weeks ago"}]'::jsonb,
 '[{"desc":"Additional pipe — 2\" sprinkler main","qty":96,"unit":"LF","rate":38,"total":3648}]'::jsonb,
 0, 0.10, true, '[]'::jsonb),

-- ── SYBJ ──
('co_sybj_001', 'SYBJ-CO-001', 'Structural beam added — N expansion grid',
 'design_change', 'steel', 'critical', 'sybj', 'executed',
 'arch', 'owner', '2026-03-20', '2026-03-28', '2026-04-01', '2026-03-27',
 34200, 34200, 2,
 'Additional W12x40 beam at north expansion grid to carry mechanical unit load.',
 'EOR directed per structural calculation revision.',
 'RFI-012', 'Spec 05 12 00', 'S-301 Rev B',
 '["pm","sub1","arch"]'::jsonb, '[]'::jsonb,
 '["SK-12_Beam.pdf","StructCalc_Rev2.pdf"]'::jsonb,
 '[{"author":"owner","text":"Approved. Add to contract.","time":"3 weeks ago"}]'::jsonb,
 '[{"desc":"W12x40 beam — 42 LF","qty":42,"unit":"LF","rate":280,"total":11760}]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

('co_sybj_002', 'SYBJ-CO-002', 'Parking expansion — NE corner 28 stalls',
 'scope_add', 'sitework', 'medium', 'sybj', 'submitted',
 'pm', null, '2026-04-10', null, null, '2026-04-25',
 56800, 0, 4,
 '28 additional parking stalls in NE corner. Full depth asphalt, striping, wheel stops.',
 'Owner email 4/8/2026 requesting addition.',
 '', 'Spec 32 12 16', 'C-201 Rev D',
 '["pm","owner","sub2"]'::jsonb, '[]'::jsonb,
 '["OwnerEmail_Parking.pdf"]'::jsonb,
 '[{"author":"pm","text":"Submitted for review. 15-day clock started 4/10.","time":"9 days ago"}]'::jsonb,
 '[{"desc":"Asphalt 3\" base + 2\" surface","qty":14000,"unit":"SF","rate":2.40,"total":33600}]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

('co_sybj_003', 'SYBJ-CO-003', 'Credit — eliminate decorative column wraps',
 'scope_del', 'finishes', 'low', 'sybj', 'approved',
 'owner', 'pm', '2026-04-05', '2026-04-12', null, '2026-04-15',
 -14200, -14200, 0,
 'Owner eliminates decorative column wraps at lobby.',
 'Owner value engineering decision.',
 '', 'Spec 09 69 00', 'A-301',
 '["pm","owner","sub4"]'::jsonb, '[]'::jsonb,
 '["ASI-08.pdf"]'::jsonb,
 '[{"author":"pm","text":"Credit confirmed.","time":"1 week ago"}]'::jsonb,
 '[{"desc":"Column wrap material credit","qty":1,"unit":"LS","rate":-8800,"total":-8800}]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

-- ── CWSJ ──
('co_cwsj_001', 'CWSJ-CO-001', 'RFI-022 beam pocket dimension correction',
 'rfi', 'concrete', 'high', 'cwsj', 'draft',
 'super', null, null, null, null, '2026-04-28',
 3400, 0, 1,
 'Architect directed beam pocket at Grid C to be 2" deeper than drawings. Core drill required after pour.',
 'Architectural direction per RFI-022 response.',
 'RFI-022', '', 'S-401',
 '["super","sub2"]'::jsonb, '[]'::jsonb,
 '["RFI-022_Response.pdf"]'::jsonb,
 '[{"author":"super","text":"Building this CO now.","time":"3 days ago"}]'::jsonb,
 '[{"desc":"Core drill — 4\" diamond bit","qty":1,"unit":"LS","rate":1200,"total":1200}]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

('co_cwsj_002', 'CWSJ-CO-002', 'Extended canopy — porte-cochère',
 'scope_add', 'framing', 'medium', 'cwsj', 'under_review',
 'pm', 'arch', '2026-04-08', null, null, '2026-04-22',
 67400, 0, 6,
 'Extend porte-cochère canopy by 12ft for better weather coverage at entry drive.',
 'Owner request from site visit 4/5.',
 '', '', 'A-105 Rev A',
 '["pm","owner","arch","sub4"]'::jsonb, '[]'::jsonb,
 '[]'::jsonb, '[]'::jsonb,
 '[{"desc":"Steel canopy framing — 12 LF ext","qty":12,"unit":"LF","rate":3200,"total":38400}]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

('co_cwsj_003', 'CWSJ-CO-003', 'Roof insulation upgrade — R-38',
 'value_eng', 'roofing', 'low', 'cwsj', 'approved',
 'pm', 'owner', '2026-03-12', '2026-03-20', null, '2026-03-22',
 22800, 22800, 0,
 'Upgrade roof insulation from R-30 to R-38 for energy performance.',
 'Value engineering — payback within 4 years at current utility rates.',
 '', 'Spec 07 21 00', 'A-401',
 '["pm","owner","sub4"]'::jsonb, '[]'::jsonb,
 '["Energy_Calc.pdf"]'::jsonb, '[]'::jsonb,
 '[{"desc":"R-38 rigid insulation","qty":42000,"unit":"SF","rate":0.45,"total":18900}]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

-- ── HIS ──
('co_his_001', 'HIS-CO-001', 'Weather delay — 7 days of heavy rain',
 'weather', 'general', 'high', 'his', 'approved',
 'super', 'owner', '2026-03-22', '2026-03-30', null, '2026-04-02',
 0, 0, 7,
 '7 consecutive days of rain 3/15-3/21 prevented concrete placement.',
 'NOAA weather records attached. Site mud photos.',
 '', '', '',
 '["pm","super","owner"]'::jsonb, '[]'::jsonb,
 '["NOAA_Weather_Mar.pdf"]'::jsonb, '[]'::jsonb,
 '[]'::jsonb,
 0, 0, false, '[]'::jsonb),

('co_his_002', 'HIS-CO-002', 'Allowance draw — signage package',
 'allowance', 'finishes', 'medium', 'his', 'executed',
 'pm', 'owner', '2026-02-28', '2026-03-05', '2026-03-10', '2026-03-05',
 18500, 18500, 0,
 'Drawdown from signage allowance for branded monument sign at entry.',
 'Per contract allowance 01 23 00.',
 '', 'Spec 10 14 00', '',
 '["pm","owner"]'::jsonb, '[]'::jsonb,
 '["Signage_Quote.pdf"]'::jsonb, '[]'::jsonb,
 '[{"desc":"Monument sign + lighting","qty":1,"unit":"LS","rate":18500,"total":18500}]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

('co_his_003', 'HIS-CO-003', 'Error — duct conflict with beam Grid F-4',
 'error_omission', 'mep', 'high', 'his', 'rejected',
 'sub3', 'arch', '2026-04-03', '2026-04-10', null, '2026-04-15',
 8900, 0, 0,
 'Main supply duct conflicts with structural beam. Reroute required.',
 'Coordination error between mechanical and structural drawings.',
 'RFI-024', '', 'M-201',
 '["pm","sub3","arch"]'::jsonb, '[]'::jsonb,
 '[]'::jsonb,
 '[{"author":"arch","text":"Responsibility lies with the MEP sub — rejecting.","time":"2 weeks ago"}]'::jsonb,
 '[]'::jsonb,
 0, 0.10, true, '[]'::jsonb),

-- ── HIBR ──
('co_hibr_001', 'HIBR-CO-001', 'Foundation redesign — soft soil conditions',
 'unforeseen', 'concrete', 'critical', 'hibr', 'approved',
 'pm', 'owner', '2026-02-05', '2026-02-18', null, '2026-02-15',
 184000, 172000, 12,
 'Soft clay at elevation -8ft requires deep foundation piles instead of spread footings.',
 'Geotech recommendation. Design revised by SEOR.',
 'RFI-003', '', 'S-201 Rev C',
 '["pm","arch","sub2"]'::jsonb, '[]'::jsonb,
 '["Geotech_v2.pdf","SEOR_Letter.pdf"]'::jsonb,
 '[{"author":"owner","text":"Approved at $172K after value engineering review.","time":"2 months ago"}]'::jsonb,
 '[{"desc":"Pile installation — 42 piles","qty":42,"unit":"EA","rate":3200,"total":134400}]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

('co_hibr_002', 'HIBR-CO-002', 'Pool deck resurfacing — premium finish',
 'owner_directed', 'finishes', 'low', 'hibr', 'draft',
 'pm', null, null, null, null, '2026-05-01',
 28400, 0, 0,
 'Upgrade pool deck from standard broom concrete to textured finish with integral color.',
 'Owner request for brand consistency.',
 '', '', 'A-502',
 '["pm","owner"]'::jsonb, '[]'::jsonb,
 '[]'::jsonb, '[]'::jsonb,
 '[]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

('co_hibr_003', 'HIBR-CO-003', 'EV charging stations — 4 Level 2 chargers',
 'scope_add', 'electrical', 'medium', 'hibr', 'under_review',
 'pm', 'owner', '2026-04-12', null, null, '2026-04-26',
 42600, 0, 3,
 '4 Level 2 EV chargers with dedicated service and signage.',
 'Brand standard update 4/1/2026.',
 '', 'Spec 26 27 26', 'E-101',
 '["pm","owner","sub3"]'::jsonb, '[]'::jsonb,
 '["EV_Spec_Update.pdf"]'::jsonb, '[]'::jsonb,
 '[{"desc":"Level 2 charger — 4 EA","qty":4,"unit":"EA","rate":5800,"total":23200}]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

-- ── HWG ──
('co_hwg_001', 'HWG-CO-001', 'Courtyard fire pit addition',
 'scope_add', 'sitework', 'low', 'hwg', 'approved',
 'owner', 'pm', '2026-03-18', '2026-03-25', null, '2026-03-30',
 19800, 19800, 2,
 'Add gas fire pit with seating wall to center of courtyard.',
 'Owner brand enhancement.',
 '', '', 'L-101',
 '["pm","owner","sub2"]'::jsonb, '[]'::jsonb,
 '["Firepit_Detail.pdf"]'::jsonb, '[]'::jsonb,
 '[{"desc":"Gas fire pit + stone wall","qty":1,"unit":"LS","rate":19800,"total":19800}]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

('co_hwg_002', 'HWG-CO-002', 'Suite kitchenette appliance upgrade',
 'owner_directed', 'plumbing', 'medium', 'hwg', 'executed',
 'pm', 'owner', '2026-02-20', '2026-03-01', '2026-03-08', '2026-03-01',
 64500, 64500, 0,
 'Upgrade all 98 suite kitchenette appliance packages from base spec to brand-preferred package.',
 'Brand requirement update.',
 '', 'Spec 11 31 00', 'A-701',
 '["pm","owner","sub3"]'::jsonb, '[]'::jsonb,
 '["Appliance_Spec.pdf"]'::jsonb, '[]'::jsonb,
 '[{"desc":"Appliance package upgrade — 98 suites","qty":98,"unit":"EA","rate":650,"total":63700}]'::jsonb,
 0, 0.10, false, '[]'::jsonb),

('co_hwg_003', 'HWG-CO-003', 'RFI response — ceiling height clarification',
 'rfi', 'framing', 'low', 'hwg', 'voided',
 'super', null, '2026-03-05', null, null, '2026-03-12',
 0, 0, 0,
 'Clarified ceiling height at corridor 2F: 9ft per architectural drawing (not 8ft-6in as questioned).',
 'No cost impact — clarification only.',
 'RFI-019', '', 'A-201',
 '["super","arch"]'::jsonb, '[]'::jsonb,
 '[]'::jsonb,
 '[{"author":"arch","text":"Clarified. No cost impact.","time":"6 weeks ago"}]'::jsonb,
 '[]'::jsonb,
 0, 0.10, false, '[]'::jsonb)

on conflict (id) do update set
  num = excluded.num,
  title = excluded.title,
  type = excluded.type,
  category = excluded.category,
  priority = excluded.priority,
  project = excluded.project,
  status = excluded.status,
  submitted_by = excluded.submitted_by,
  reviewed_by = excluded.reviewed_by,
  submitted_date = excluded.submitted_date,
  reviewed_date = excluded.reviewed_date,
  executed_date = excluded.executed_date,
  due_date = excluded.due_date,
  requested_amt = excluded.requested_amt,
  approved_amt = excluded.approved_amt,
  schedule_impact = excluded.schedule_impact,
  description = excluded.description,
  justification = excluded.justification,
  linked_rfi = excluded.linked_rfi,
  linked_spec = excluded.linked_spec,
  linked_drawing = excluded.linked_drawing,
  assignees = excluded.assignees,
  photos = excluded.photos,
  attachments = excluded.attachments,
  comments = excluded.comments,
  line_items = excluded.line_items,
  owner_markup = excluded.owner_markup,
  gc_markup = excluded.gc_markup,
  is_sub_co = excluded.is_sub_co,
  sub_cos = excluded.sub_cos;
